### ISSUE TITLE
Namespace CISCP not present

### ISSUE THREAD

**Issue by Danko90** [CybOXProject/mixbox#38]
Hi,
I had to poll data from a STIX repository but I got an error because CISCP Namespace isn't present in there.
I added it
`
NS_CISCP_INSTANCE = Namespace('http://www.us-cert.gov/ciscp', 'CISCP', '')
`
in the file namespaces.py
Everything worked well.
Could you please let me know if I did it correctly or not?

Thank you
Danilo

**Comment by gtback** [comment]
Hi, @Danko90 . Thanks for the question!

While that approach (modifying mixbox directly) certainly works, mixbox was designed so that you can add namespaces from outside (for instance, in your own code). An example of this is shown in the (non-default) AIS namespaces in python-stix.

You should be able to do something similar to [this code](https://github.com/STIXProject/python-stix/blob/2d7b0d4d292bf5c519c9a43e52125f896dde6f5c/stix/extensions/marking/ais.py#L105-L119) in your own code:

```
from stix.utils import nsparser
import mixbox.namespaces

ns = mixbox.namespaces.Namespace('http://www.us-cert.gov/ciscp', 'CISCP', '')

nsparser.STIX_NAMESPACES.add_namespace(ns)
mixbox.namespaces.register_namespace(ns)
```

I'm going to close this issue, but if you have problems, feel free to re-open it. Thanks again!
