### ISSUE TITLE
NamespaceNotFoundError causes exception in mixbox-1.0.2-py2.7

### ISSUE THREAD

**Issue by sglatlas** [CybOXProject/mixbox#39]
I ran into issues parsing some STIX files:
 
File "/usr/lib/python2.7/site-packages/mixbox-1.0.2-py2.7.egg/mixbox/namespaces.py", line 859, in lookup_name
return __ALL_NAMESPACES.preferred_prefix_for_namespace(ns_uri)
File "/usr/lib/python2.7/site-packages/mixbox-1.0.2-py2.7.egg/mixbox/namespaces.py", line 291, in preferred_prefix_for_namespace
ni = self.__lookup_uri(ns_uri)
File "/usr/lib/python2.7/site-packages/mixbox-1.0.2-py2.7.egg/mixbox/namespaces.py", line 207, in __lookup_uri
raise NamespaceNotFoundError(uri)
mixbox.namespaces.NamespaceNotFoundError: Namespace not found: http://redacted/redacted

 It turns out preferred_prefix_for_namespace(self, ns_uri) doesn't have exception handling.  I added a try:/except:/else: so it could fail gracefully:
```
    def preferred_prefix_for_namespace(self, ns_uri):
        """Get the "preferred" prefix for the given namespace.  Returns None
        if the preference is to use as the default namespace."""
        # Added try/except to avoid crashing if namespace not found
        try:
                ni = self.__lookup_uri(ns_uri)
        except:
                return None
        else:
                return ni.preferred_prefix
```

**Comment by gtback** [comment]
Thanks, @sglatlas!

I agree that the docstring of that function doesn't match it's behavior, but I'm curious what is actually intended by that function and why that error hasn't come up before. Do you know if this was a namespace used for an ID or something else? 

In other words, despite what the function docstring says, will returning `None` cause later problems down the line, depending on where it's used? If you can provide me a minimal (redacted if necessary) STIX file that demonstrates the issue, that will help me ensure it gets fixed in the right place.

**Comment by sglatlas** [comment]
Hello Greg,

Sorry for the delayed response.  I’m using a script to extract STIX indicators/observables and export them into a format that our SIEM understands.  I suspect that in this case, the STIX file probably had a typo in the namespace name, or perhaps used a tag incorrectly and caused the method to fail.  I have no idea if returning None will wreak havoc… it doesn’t for me, but I don’t know how/if it would impact others.  I’m still relatively new to the world of STIX, and picked up the extraction script second-hand, so I’ve been trying to make the script a bit more tolerant of typos and other unintentional issues between the keyboard and the seat.

I redacted one of the files, and attached it for your testing.  If the issue is glaringly obvious, please let me know, and I’ll try to add some code to the extraction script to handle it properly before the method is invoked.

Thanks for investigating!

**Comment by gtback** [comment]
Thanks @sglatlas. I think the attachment got lost when replying to GitHub. Can you send it to stix@mitre.org (and include a link to this issue so that everyone else who gets the email doesn't get confused)?

If it's something easy to fix on your end before parsing with python-stix/python-cybox/mixbox, that's probably better than adapting those libraries to accept invalid content and *hoping* things work out correctly. I'm not opposed to making changes if that makes the most sense, though.

**Comment by gtback** [comment]
@sglatlas I don't think I ever saw an email from you to stix@mitre.org. Are you still having this problem?

If you sent a message before, it may have gotten caught by a spam filter, so would you mind re-sending?

**Comment by gtback** [comment]
Based on some more investigation, the correct approach is probably to register the namespace with both mixbox and python-stix; that should prevent this error from occuring, rather than needing to catch or ignore it.

If you have any questions or need any help, don't hesitate to re-open this !
